name: weather-data-pipeline-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h7c4b9e2_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py310h69bd2ac_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - comm=0.2.3=pyhe01879c_0
  - cryptography=46.0.3=py310hb288b08_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastapi=0.124.2=hc0e8453_0
  - fastapi-cli=0.0.16=pyhcf101f3_1
  - fastapi-core=0.124.2=pyhcf101f3_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - greenlet=3.3.0=py310hea6c23e_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py310h7c4b9e2_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyha191276_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libprotobuf=5.29.3=h7460b1f_3
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.2=h5347b49_1
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mysql=9.3.0=h27aab58_0
  - mysql-client=9.3.0=he0572af_0
  - mysql-common=9.3.0=h266115a_0
  - mysql-connector-python=9.3.0=py310h0070a79_1
  - mysql-devel=9.3.0=h266115a_0
  - mysql-libs=9.3.0=he0572af_0
  - mysql-server=9.3.0=hcdea623_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.5.0=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.3=py310h139afa4_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hd8f68c5_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymysql=1.1.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.17.0=pyhcf101f3_0
  - rpds-py=0.30.0=py310hd8f68c5_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlalchemy=2.0.45=py310h7c4b9e2_0
  - sqlmodel=0.0.31=pyhcf101f3_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.50.0=pyhfdc7a7d_0
  - terminado=0.18.1=pyh0d859eb_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.3=py310h7c4b9e2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.22.1=py310h7c4b9e2_1
  - watchfiles=1.1.1=py310hdfeec95_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=15.0.1=py310h139afa4_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - altair==6.0.0
      - backcall==0.2.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - debugpy==1.8.18
      - docopt==0.6.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - ipython==8.12.3
      - narwhals==2.14.0
      - numpy==2.2.6
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - pipreqs==0.5.0
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydeck==0.9.1
      - python-json-logger==4.0.0
      - smmap==5.0.2
      - streamlit==1.52.2
      - tenacity==9.1.2
      - tinycss2==1.4.0
      - toml==0.10.2
      - urllib3==2.6.2
      - watchdog==6.0.0
      - yarg==0.1.9
